[workspace]
members = ["core", "macros", "hw"]
resolver = "2"

[profile.dev]
opt-level = 3


[workspace.dependencies]
nalgebra = { version = "0.33.2", features = ["rayon", "serde-serialize"]}
plotters = "0.3.7"
macroquad = "0.4.14"
osqp = "1.0.1"
