[package]
name = "symbolic_services"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra = {workspace = true}
serde = {workspace = true}
serde_json = {workspace = true}
rand = { workspace = true}
rayon = {workspace = true}

fasteval = "0.2.4"

[dev-dependencies]
proptest = "1.4"