[package]
name = "control-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
macros = { path = "../macros"}

nalgebra = {workspace = true}
plotters = {workspace = true}
macroquad = {workspace = true}
osqp = {workspace = true}

async-trait = "0.1"
serde = {version ="1.0", features = ["derive"]}
serde_derive = "1.0"
serde_json = "1.0.140"
toml = "0.8"
fasteval = "0.2.4"
log = "0.4"
env_logger = "0.11" 
rand = "0.8"
once_cell = "1.18"
rand_distr = "0.4"
rayon = "1.7"




[dev-dependencies]
proptest = "1.4"
approx = "0.5"

